services:
  postgres:
    container_name: container_postgres
    image: postgres:latest
    hostname: localhost
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  pgadmin:
    container_name: container_pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - "postgres"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data: